import { SiChai, SiNicehash } from "react-icons/si";

const content = {
  th: {
    home: "หน้าแรก",
    about: "เกี่ยวกับฉัน",
    portfolio: "ผลงาน",
    contact: "ติดต่อ",
    skill: "ทักษะ",
    skillContent: "ทักษะของฉัน",
    homeContent: "ยินดีต้อนรับสู่หน้าแรก",
    aboutContent: "นี่คือส่วนเกี่ยวกับฉัน",
    portfolioContent: "นี่คือผลงานของฉัน",
    contactContent: "ติดต่อฉันได้ที่นี่",
    intro:"สวัสดี,ฉันคือ",
    fullname: "ธรรมชาติ มิ่งขวัญ",
    fullstack: "นักพัฒนา Full Stack",
    downloadCV: "ดาวน์โหลดประวัติย่อ",
    experienced: "นักพัฒนาเว็บที่มีประสบการณ์ มีความหลงใหลในการสร้างแอปพลิเคชันที่ทันสมัยและใช้งานง่าย",
    nickname:"แคน",
    position:"โปรแกรมเมอร์",
    major:"เทคโนโลยีสารสนเทศ",
    univercity:"มหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตเฉลิมพระเกียรติ จังหวัดสกลนคร",
    age: "อายุ 25 ปี",
    birday: "เกิดวันที่ 28 มิถุนายน 2543",
    myinformation: "ข้อมูลส่วนตัว",
    myfullname:"ชื่อ : ธรรมชาติ มิ่งขวัญ",
    mynickname:"ชื่อเล่น : แคน",
    education: "การศึกษา",
    basorloderee: "ปริญญาตรี",
    higschschool: "มัธยมศึกษาตอนปลาย",
    school: "โรงเรียนเมืองกลางประชานุกูล",
    experice: "ประสบการณ์การทำงาน",
    sonyposition:"ผู้เชี่ยวชาญด้านไอที",
    sony:'<b>บริษัท โซนี่ เทตโนโลยี (ประเทศไทย) จำกัด</b> <br /> 04/2568 - ปัจจุบัน <br /> พัฒนาเว็บFull Stack',
    maejardposition:"ผู้จัดการฝ่ายไอที",
    maejard:'<b>บริษัท แม่จ๊าดฟาร์ม จำกัด </b> <br /> 04/2567 - 11/2567 <br /> ดูแลและพัฒนาระบบไอที เว็บไซต์ ระบบIoT ระบบCCTV และระบบNetwork ',
    gobalhouseposition:"โปรแกรมเมอร์",
    gobalhouse: '<b>บริษัท สยามโกลบอลเฮ้าส์ จำกัด (มหาชน)</b> <br /> 08/2566 - 11/2566 <br /> พัฒนาโมบายแอพพลิเคชั่น Full Stack',
    kce: '<b>บริษัท เคซีอี อิเลคโทรนิคส์ จำกัด (มหาชน)</b> <br /> 03/2566 - 06/2566 <br /> พัฒนาเว็บแอพพลิเคชั่น Full Stack',
    contacts:"ข้อมูลการติดต่อ",
    address:"227 หมู่ 21 ตำบลกุดชุม อำเภอกุดชุม จังหวัดยโสธร 35140",
    phone: "โทรศัพท์: 0638830905",
    sex: "เพศ: ชาย",
    transcript:"ทรานสคริปต์",
    submit:"ส่งขคำขอ",
    op_all: "ทั้งหมด",
    op_thai:"ภาษาไทย",
    op_eng:"ภาษาอังกฤษ",
    catyegiry_doc: "ประเภทเอกสาร",
    fo_name: "ชื่อ-นามสกุล",
    fo_email: "อีเมล",
  },
  en: {
    home: "Home",
    about: "About Me",
    portfolio: "Portfolio",
    contact: "Contact",
    skill: "Skills",
    skillContent: "My Skills",
    homeContent: "Welcome to Home Section",
    aboutContent: "This is About Me section",
    portfolioContent: "This is my Portfolio",
    contactContent: "Get in touch with me",
    intro: "Hello, I'm",
    fullname: "Thammachat Mingkhwan",
    fullstack: "Full Stack Developer",
    downloadCV: "Download CV",
    experienced: "Experienced web developer passionate about creating modern and user-friendly applications",
    nickname: "Khaen",
    position:"Programmer",
    major:"Information Technology",
    univercity:"Kasetsart University Sakon Nakhon Campus",
    age: "25 years old",
    birday: "June 28, 2000",
    myinformation: "My Information",
    myfullname: "Full Name: Thammachat Mingkhwan",
    mynickname: "Nickname: Khaen",
    education: "Education",
    basorloderee: "Bachelor's Degree",
    higschschool: "High School",
    school: "Muang Klang Prachanukool School",
    experice: "Work Experience",
    sony: '<b>Sony Technology (Thailand) Co., Ltd.</b> <br /> 04/2025 - Present <br /> Full Stack Web Development',
    sonyposition:"IT Specialist",
    maejardposition:"IT Manager",
    maejard: '<b>Maejard Farm Co., Ltd.</b> <br /> 04/2024 - 11/2024 <br /> Managed and developed IT systems, websites, IoT systems, CCTV systems, and network systems',
    gobalhouseposition:"Programmer",
    gobalhouse: '<b>Siam Global House Public Company Limited</b> <br /> 08/2023 - 11/2023 <br /> Developed Full Stack Mobile Applications',
    kce: '<b>KCE Electronics Public Company Limited</b> <br /> 03/2023 - 06/2023 <br /> Developed Full Stack Web Applications',
    contacts: "Contact Information",
    address: "227 Moo 21, Kud Chum Subdistrict, Kud Chum District, Yasothon Province 35140",
    phone: "Phone: 0638830905",
    sex:"male",
    transcript: "Transcript",
    submit: "Submit Request",
    op_all: "All",
    op_thai: "Thai",   
    op_eng: "English",
    catyegiry_doc: "Document Category",
    fo_name: "Full Name",
    fo_email: "Email",

 },
};

export default content;
